version: '3'
services:

  #PHP Service
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file: .env.local
    environment:
      - SERVICE_NAME=app
      - SERVICE_TAGS=dev
    ports: 
      - "9000:9000"
    restart: unless-stopped
    tty: true
    volumes:
      - ./api:/var/www
      - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    working_dir: /var/www

  #Nginx Service
  webserver:
    depends_on:
      - frontend
      - api
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    tty: true
    volumes:
      - ./api:/var/www
      - ./config/nginx/conf.d:/etc/nginx/conf.d

  #MySQL Service
  db:
    env_file: .env.local
    environment:
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    restart: unless-stopped
    tty: true
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf

  #React Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app